---
# WebBoost Martinique - Déploiement automatique GitHub → 02switch
# Architecture : HTML/CSS/JS + API PHP

deployment:
  tasks:
    # Préparation environnement
    - export DEPLOYPATH=/home/weboostmartinique/public_html/
    - echo "🚀 Début déploiement WebBoost Martinique..."
    
    # Nettoyage dossier cible (sécurisé)
    - /bin/find $DEPLOYPATH -maxdepth 1 -name "*.html" -delete 2>/dev/null || true
    - /bin/find $DEPLOYPATH -maxdepth 1 -name "*.css" -delete 2>/dev/null || true
    - /bin/find $DEPLOYPATH -maxdepth 1 -name "*.js" -delete 2>/dev/null || true
    - /bin/rm -rf $DEPLOYPATH/assets/ 2>/dev/null || true
    - /bin/rm -rf $DEPLOYPATH/api/ 2>/dev/null || true
    
    # Déploiement fichiers principaux
    - echo "📄 Copie fichiers HTML..."
    - /bin/cp *.html $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/cp robots.txt $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp sitemap.xml $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp favicon.ico $DEPLOYPATH/ 2>/dev/null || true
    
    # Déploiement assets (structure préservée)
    - echo "🎨 Copie assets (CSS, JS, images)..."
    - /bin/cp -R assets/ $DEPLOYPATH/
    
    # Déploiement API backend
    - echo "⚙️ Copie API backend..."
    - /bin/cp -R api/ $DEPLOYPATH/
    
    # Variables environnement (sécurisé)
    - /bin/cp .env $DEPLOYPATH/ 2>/dev/null || echo "⚠️ Fichier .env non trouvé - normal en développement"
    
    # Permissions fichiers (sécurité 02switch)
    - echo "🔐 Configuration permissions..."
    - find $DEPLOYPATH -name "*.php" -exec chmod 755 {} \;
    - find $DEPLOYPATH -name "*.html" -exec chmod 644 {} \;
    - find $DEPLOYPATH -name "*.css" -exec chmod 644 {} \;
    - find $DEPLOYPATH -name "*.js" -exec chmod 644 {} \;
    - find $DEPLOYPATH -name "*.png" -exec chmod 644 {} \;
    - find $DEPLOYPATH -name "*.jpg" -exec chmod 644 {} \;
    - find $DEPLOYPATH -name "*.jpeg" -exec chmod 644 {} \;
    - find $DEPLOYPATH -name "*.gif" -exec chmod 644 {} \;
    - find $DEPLOYPATH -name "*.svg" -exec chmod 644 {} \;
    - find $DEPLOYPATH -name "*.ico" -exec chmod 644 {} \;
    - find $DEPLOYPATH -name "*.xml" -exec chmod 644 {} \;
    - find $DEPLOYPATH -name "*.txt" -exec chmod 644 {} \;
    - chmod 644 $DEPLOYPATH/.htaccess 2>/dev/null || true
    - chmod 600 $DEPLOYPATH/.env 2>/dev/null || true
    
    # Nettoyage fichiers développement
    - echo "🧹 Nettoyage fichiers développement..."
    - /bin/rm -rf $DEPLOYPATH/.git/ 2>/dev/null || true
    - /bin/rm -rf $DEPLOYPATH/node_modules/ 2>/dev/null || true
    - /bin/rm -rf $DEPLOYPATH/.vscode/ 2>/dev/null || true
    - /bin/rm -rf $DEPLOYPATH/.idea/ 2>/dev/null || true
    - /bin/rm -f $DEPLOYPATH/package*.json 2>/dev/null || true
    - /bin/rm -f $DEPLOYPATH/yarn.lock 2>/dev/null || true
    - /bin/rm -f $DEPLOYPATH/*.log 2>/dev/null || true
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml 2>/dev/null || true
    
    # Vérification structure déployée
    - echo "🔍 Vérification déploiement..."
    - ls -la $DEPLOYPATH/
    - test -f $DEPLOYPATH/index.html && echo "✅ index.html déployé"
    - test -d $DEPLOYPATH/assets/ && echo "✅ assets déployés"
    - test -d $DEPLOYPATH/api/ && echo "✅ API déployée"
    - test -f $DEPLOYPATH/.htaccess && echo "✅ .htaccess configuré"
    
    # Test basique de structure
    - test -f $DEPLOYPATH/assets/css/main.css && echo "✅ CSS principal présent"
    - test -f $DEPLOYPATH/assets/js/chatbot.js && echo "✅ Chatbot Élise présent"
    - test -f $DEPLOYPATH/api/chat.php && echo "✅ API chat présente"
    
    # Log final
    - echo "🎉 WebBoost Martinique déployé avec succès sur 02switch à $(date)"
    - echo "📝 Déploiement terminé" >> $DEPLOYPATH/deployment.log
    - echo "🌐 Site disponible : https://weboostmartinique.com"